Added the option to display or hide a header in a model
bupy7/yii2-pages pull request #17
Opened 2018-09-27 20:52 UTC by bupy7

2018-09-27 20:53 UTC, bupy7 commented
Ongoing by https://github.com/bupy7/yii2-pages/pull/15

2018-09-27 20:57 UTC, bupy7 commented
Hello @zacksleo , @amavis442 and @maxxer ! Could you please check translation of DISPLAY_TITLE message at the pull-request?

2018-09-28 01:39 UTC, zacksleo requested changes
`src/messages/zh-TW/core.php`

2018-09-28 01:39 UTC, zacksleo commented on src/messages/zh-TW/core.php
> +    'DISPLAY_TITLE' => '显示标题',
should be 
```php
'DISPLAY_TITLE' => '顯示標題',
```

2018-09-29 12:00 UTC, bupy7 commented on src/messages/zh-TW/core.php
> +    'DISPLAY_TITLE' => '显示标题',
Thanks a lot!

2018-09-29 12:16 UTC, closed without merging

2018-09-29 12:18 UTC, bupy7 commented
Realased https://github.com/bupy7/yii2-pages/releases/tag/v1.4.0